name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@2253d9c9310442c09975d64615591b5b381da6e7  # yamllint disable-line rule:line-length
        with:
          pixi-version: v0.71.3
          cache: false
          frozen: true

      - name: Run linting
        run: |
          pixi run lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@2253d9c9310442c09975d64615591b5b381da6e7  # yamllint disable-line rule:line-length
        with:
          pixi-version: v0.71.3
          cache: false
          frozen: true
      - name: Run tests
        run: |
          pixi run test-w-cov
